---
# tasks file for ansible-role-sshd

- include_vars: "{{ ansible_os_family }}.yml"

- include: install-FreeBSD.yml

- name: Create sshd.conf
  template:
    src: sshd_config.j2
    dest: "{{ sshd_conf }}"
    validate: /usr/sbin/sshd -t
  notify: Restart sshd

- name: Start sshd
  service:
    name: "{{ sshd_service }}"
    enabled: true
    state: started
